FROM amazoncorretto:21.0.4-alpine3.18

WORKDIR /app

ENV DB_URL=${DB_URL}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV PHARMACY_SERVICE_URL=${PHARMACY_SERVICE_URL}
ENV PATIENT_SERVICE_URL=${PATIENT_SERVICE_URL}
ENV SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
ENV GOOGLE_API_KEY=${GOOGLE_API_KEY}
ENV PORT=${PORT_FINDER}

COPY target/FarmaNear-Finder-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]